name: zika-crossfilter
channels:
  - conda-forge
  - defaults
dependencies:
  - certifi=2019.6.16
  - chardet=3.0.4
  - click=7.0
  - dash=1.2.0
  - dash-core-components=1.1.2
  - dash-html-components=1.0.1
  - dash-renderer=1.0.1
  - dash-table=4.2.0
  - decorator=4.4.0
  - flask=1.1.1
  - flask-compress=1.4.0
  - gunicorn=19.9.0
  - idna=2.8
  - ipython
  - itsdangerous=1.1.0
  - jinja2=2.10.1
  - jsonschema=3.0.2
  - jupyter
  - markupsafe=1.1.1
  - nbformat=4.4.0
  - numpy=1.17.1
  - pandas=0.25.1
  - plotly=4.1.1
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.2
  - requests=2.22.0
  - six=1.12.0
  - traitlets=4.3.2
  - urllib3=1.25.3
  - werkzeug
  - pip:
    - DateTime==4.3
